### How does the time of day that various citations tend to take take place at fluctuate throughout the year?

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pyodbc
import pandas as pd
import seaborn as sns
import datetime
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.0f}'.format

# databaseConnection = 'DRIVER={SQL Server}; SERVER=ServerName; Database=DatbaseName; UID=UserId; PWD=password;'
connection = pyodbc.connect('DRIVER={SQL Server};SERVER=WINDOWS-A6S01I2\SQLEXPRESS;DATABASE=City_of_Scottsdale;Trusted_Connection=yes;')
cursor = connection.cursor()

# SQL query to import all citation data
citations = '''
  select *
from [dbo].[spd_PDCitations$]
'''
citations = pd.read_sql(citations, connection)
connection.close()

citations['Month'] = citations['Citation Date'].dt.month
citations['Week'] = citations['Citation Date'].dt.week

KeyError: 'Hour_of_Day'

In [3]:
citations.shape

(35752, 24)

In [5]:
citations.head()

,tcmainid,Citation #,Citation Date,Citation Time,Arizona Statute Code,Charge Description,Citation Type Code,Citation Type Description,Officer Badge #,Street Number,Street,City,State,Zip,District,Beat,Zone,Cited Person,Cited Person Age,Cited Person Race,Cited Person Sex,Cited Person Ethnicity,Month,Week
0,621784,2065379,2018-06-23,204,13-1203A1,Assault-Intentional/Recklessly Injure,CR,Criminal,1489,1xxx,N Granite Reef Rd,Scottsdale,AZ,nan,D1,2,412,"Hill, Julie",25,I,F,N,6,25
1,621797,2063172,2018-06-23,928,13-3415A,Drug Paraphernalia-Possess/Use,CR,Criminal,1214,7xxx,N Hayden Rd,Scottsdale,AZ,nan,D3,10,2504,"Mc Cuan, Michael",51,W,M,N,6,25
2,621806,2056700,2018-06-23,1053,28-701A,Failure to Control Speed to Avoid A Collision,CV,Civil Traffic,1360,xxx,E Indian Bend Rd / N Scottsdale Rd,Scottsdale,AZ,nan,D3,10,2501,"Glasscock, James",60,W,M,N,6,25
3,621847,2050143,2018-06-23,2345,19-19A,Urinate/Defecate In Public,MC,Municipal Code,1345,4xxx,N Saddlebag Tr,Scottsdale,AZ,nan,D2,6,904,"Still, Marcus",22,B,M,N,6,25
4,621878,2063174,2018-06-24,927,28-3473A,Suspended/Revoked D.L.,CT,Criminal Traffic,1214,8xxx,E McDonald DR,Scottsdale,AZ,nan,D2,8,2205,"Chacon, Kimberly",48,W,F,N,6,25

In [27]:
# filter for only groups with at least 10 citations over the course of the year
citations_filtered = citations.groupby(['Charge Description', 'Week']).filter(lambda x: x['Charge Description'].count() > 9)

citations_filtered.head(50)

citations_filtered.groupby(['Charge Description', 'Week'])['Citation Time'].agg(['var', 'count'])

                                                 var  count
Charge Description                      Week
Adequate Windshield Required-Automobile 39    244140     11
Amended Charge                          5     409896     10
Assault-Intentional/Recklessly Injure   2    1057696     10
                                        4     589522     10
Criminal Trespass 3rd Deg-Property      5     534567     11
DUI-Impaired to Slightest Degree        1     898620     54
                                        2     994650     34
                                        3     883547     46
                                        4    1039274     42
                                        5     944347     68
                                        6     920874     26
                                        7     940814     17
                                        8     880225     23
                                        9     997868     15
                                        10    975351     25
                                        11    666142     28
                                        12   1016225     20
                                        13    978199     23
                                        14   1115457     21
                                        15   1076708     26
                                        16   1079738     24
                                        17    911818     22
                                        18    950780     30
                                        19    881602     23
                                        20    767453     24
                                        21   1082954     27
                                        22    643181     23
                                        23    916210     27
                                        24    992001     29
                                        25    897224     22
...                                              ...    ...
Urinate/Defecate In Public              46    874896     14
                                        47    831337     22
                                        48    511548     17
                                        49    117406     13
                                        50    706412     13
                                        51    368076     12
                                        52    611395     12
Void Charge                             1     486584     12
                                        2     409319     21
                                        3     257882     22
                                        4     503598     11
                                        6     465362     14
                                        18    435375     11
                                        20    310167     12
                                        38    423943     11
                                        39    257459     13
                                        40    164672     14
                                        41    291336     22
                                        42    193911     22
                                        43    591978     10
                                        44    542535     19
                                        45    597667     12
                                        46    249538     13
                                        47     83916     14
                                        48    161459     12
                                        49    218565     13
                                        50    669541     13
                                        51    138978     18
                                        52    207685     11
Waste of Finite Resource <=65mph        21    120271     13

[724 rows x 2 columns]